[steering]
nevent = 20000
pinecone = 70
run_number = 0

[geometry]
geo_spline_path = "/n/home02/thomwg11/tambo/TAMBO-MC/resources/tambo_spline.jld2"
tambo_coordinates = [-15.622267, -72.279397] # Larger valley, lat, long in degrees
plane_orientation = [0.5172072191801592, -0.03577867639105598, 0.8551120270137889] # Larger valley

[injection]
pdg = 16
gamma = 3.0
emin = 3.0e5 # GeV
emax = 1.0e9
thetamin = 0 # degrees
thetamax = 117 # degrees
phimin = 90 # degrees
phimax = 290 # degrees
r_injection = 2000.0 # m
l_endcap = 1000.0 # m
xs_dir = "/n/home02/thomwg11/tambo/TAMBO-MC/resources/cross_sections/tables/"
xs_model = "csms"
interaction = "CC"
track_progress = false

[proposal]
ecut = -1 # GeV. Negative <-> Infinity
vcut = 1e-2
do_interpolate = true
do_continuous = true
tablespath = "/n/home02/thomwg11/tambo/TAMBO-MC/resources/proposal_tables/"
track_progress = false

[corsika]
should_run_corsika = false
parallelize_corsika = false
#batch_submit_corsika = true
thinning = 1.0e-6
hadron_model = "SIBYLL-2.3d"
hadron_ecut = 0.05 # GeV
em_ecut = 0.001 # GeV
photon_ecut = 0.001 # GeV
mu_ecut = 0.05 # GeV
corsika_path = "_TAMBOSIM_PATH_/resources/corsika/src/build/tambo_shower"
obs_mesh_path = "_TAMBOSIM_PATH_/resources/injection_region_corsika.ply"
terrain_mesh_path = "_TAMBOSIM_PATH_/resources/terrain_corsika.ply"
track_progress = false



