########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(cli11_COMPONENT_NAMES "")
if(DEFINED cli11_FIND_DEPENDENCY_NAMES)
  list(APPEND cli11_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES cli11_FIND_DEPENDENCY_NAMES)
else()
  set(cli11_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(cli11_PACKAGE_FOLDER_RELWITHDEBINFO "/n/home09/tkrishnan/.conan2/p/cli11f6338b3142f74/p")
set(cli11_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(cli11_INCLUDE_DIRS_RELWITHDEBINFO "${cli11_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(cli11_RES_DIRS_RELWITHDEBINFO )
set(cli11_DEFINITIONS_RELWITHDEBINFO )
set(cli11_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(cli11_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(cli11_OBJECTS_RELWITHDEBINFO )
set(cli11_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(cli11_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(cli11_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(cli11_LIB_DIRS_RELWITHDEBINFO )
set(cli11_BIN_DIRS_RELWITHDEBINFO )
set(cli11_LIBRARY_TYPE_RELWITHDEBINFO UNKNOWN)
set(cli11_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(cli11_LIBS_RELWITHDEBINFO )
set(cli11_SYSTEM_LIBS_RELWITHDEBINFO )
set(cli11_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(cli11_FRAMEWORKS_RELWITHDEBINFO )
set(cli11_BUILD_DIRS_RELWITHDEBINFO )
set(cli11_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(cli11_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${cli11_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${cli11_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(cli11_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${cli11_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${cli11_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${cli11_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(cli11_COMPONENTS_RELWITHDEBINFO )