########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

list(APPEND eigen_COMPONENT_NAMES Eigen3::Eigen)
list(REMOVE_DUPLICATES eigen_COMPONENT_NAMES)
if(DEFINED eigen_FIND_DEPENDENCY_NAMES)
  list(APPEND eigen_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES eigen_FIND_DEPENDENCY_NAMES)
else()
  set(eigen_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(eigen_PACKAGE_FOLDER_RELWITHDEBINFO "/n/home09/tkrishnan/.conan2/p/eigen5481853932f72/p")
set(eigen_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(eigen_INCLUDE_DIRS_RELWITHDEBINFO "${eigen_PACKAGE_FOLDER_RELWITHDEBINFO}/include/eigen3")
set(eigen_RES_DIRS_RELWITHDEBINFO )
set(eigen_DEFINITIONS_RELWITHDEBINFO )
set(eigen_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(eigen_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(eigen_OBJECTS_RELWITHDEBINFO )
set(eigen_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(eigen_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(eigen_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(eigen_LIB_DIRS_RELWITHDEBINFO )
set(eigen_BIN_DIRS_RELWITHDEBINFO )
set(eigen_LIBRARY_TYPE_RELWITHDEBINFO UNKNOWN)
set(eigen_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(eigen_LIBS_RELWITHDEBINFO )
set(eigen_SYSTEM_LIBS_RELWITHDEBINFO m)
set(eigen_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(eigen_FRAMEWORKS_RELWITHDEBINFO )
set(eigen_BUILD_DIRS_RELWITHDEBINFO )
set(eigen_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(eigen_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${eigen_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${eigen_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(eigen_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${eigen_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${eigen_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${eigen_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(eigen_COMPONENTS_RELWITHDEBINFO Eigen3::Eigen)
########### COMPONENT Eigen3::Eigen VARIABLES ############################################

set(eigen_Eigen3_Eigen_INCLUDE_DIRS_RELWITHDEBINFO "${eigen_PACKAGE_FOLDER_RELWITHDEBINFO}/include/eigen3")
set(eigen_Eigen3_Eigen_LIB_DIRS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_BIN_DIRS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_LIBRARY_TYPE_RELWITHDEBINFO UNKNOWN)
set(eigen_Eigen3_Eigen_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(eigen_Eigen3_Eigen_RES_DIRS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_DEFINITIONS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_OBJECTS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(eigen_Eigen3_Eigen_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(eigen_Eigen3_Eigen_LIBS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_SYSTEM_LIBS_RELWITHDEBINFO m)
set(eigen_Eigen3_Eigen_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_FRAMEWORKS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_DEPENDENCIES_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(eigen_Eigen3_Eigen_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(eigen_Eigen3_Eigen_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${eigen_Eigen3_Eigen_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${eigen_Eigen3_Eigen_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${eigen_Eigen3_Eigen_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(eigen_Eigen3_Eigen_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${eigen_Eigen3_Eigen_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${eigen_Eigen3_Eigen_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")