########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(lz4_COMPONENT_NAMES "")
if(DEFINED lz4_FIND_DEPENDENCY_NAMES)
  list(APPEND lz4_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES lz4_FIND_DEPENDENCY_NAMES)
else()
  set(lz4_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(lz4_PACKAGE_FOLDER_RELWITHDEBINFO "/n/home09/tkrishnan/.conan2/p/b/lz414b3da346b6ce/p")
set(lz4_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(lz4_INCLUDE_DIRS_RELWITHDEBINFO )
set(lz4_RES_DIRS_RELWITHDEBINFO )
set(lz4_DEFINITIONS_RELWITHDEBINFO )
set(lz4_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(lz4_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(lz4_OBJECTS_RELWITHDEBINFO )
set(lz4_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(lz4_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(lz4_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(lz4_LIB_DIRS_RELWITHDEBINFO "${lz4_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(lz4_BIN_DIRS_RELWITHDEBINFO )
set(lz4_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(lz4_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(lz4_LIBS_RELWITHDEBINFO lz4)
set(lz4_SYSTEM_LIBS_RELWITHDEBINFO )
set(lz4_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(lz4_FRAMEWORKS_RELWITHDEBINFO )
set(lz4_BUILD_DIRS_RELWITHDEBINFO )
set(lz4_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(lz4_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${lz4_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${lz4_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(lz4_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${lz4_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${lz4_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${lz4_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(lz4_COMPONENTS_RELWITHDEBINFO )