########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(bzip2_COMPONENT_NAMES "")
if(DEFINED bzip2_FIND_DEPENDENCY_NAMES)
  list(APPEND bzip2_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES bzip2_FIND_DEPENDENCY_NAMES)
else()
  set(bzip2_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(bzip2_PACKAGE_FOLDER_RELWITHDEBINFO "/n/home09/tkrishnan/.conan2/p/b/bzip286e47bada02be/p")
set(bzip2_BUILD_MODULES_PATHS_RELWITHDEBINFO "${bzip2_PACKAGE_FOLDER_RELWITHDEBINFO}/lib/cmake/conan-official-bzip2-variables.cmake")


set(bzip2_INCLUDE_DIRS_RELWITHDEBINFO "${bzip2_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(bzip2_RES_DIRS_RELWITHDEBINFO )
set(bzip2_DEFINITIONS_RELWITHDEBINFO )
set(bzip2_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(bzip2_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(bzip2_OBJECTS_RELWITHDEBINFO )
set(bzip2_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(bzip2_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(bzip2_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(bzip2_LIB_DIRS_RELWITHDEBINFO "${bzip2_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(bzip2_BIN_DIRS_RELWITHDEBINFO )
set(bzip2_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(bzip2_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(bzip2_LIBS_RELWITHDEBINFO bz2)
set(bzip2_SYSTEM_LIBS_RELWITHDEBINFO )
set(bzip2_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(bzip2_FRAMEWORKS_RELWITHDEBINFO )
set(bzip2_BUILD_DIRS_RELWITHDEBINFO )
set(bzip2_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(bzip2_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${bzip2_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${bzip2_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(bzip2_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${bzip2_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${bzip2_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${bzip2_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(bzip2_COMPONENTS_RELWITHDEBINFO )