########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(re2_COMPONENT_NAMES "")
if(DEFINED re2_FIND_DEPENDENCY_NAMES)
  list(APPEND re2_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES re2_FIND_DEPENDENCY_NAMES)
else()
  set(re2_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(re2_PACKAGE_FOLDER_RELWITHDEBINFO "/n/home09/tkrishnan/.conan2/p/b/re27cd2c5152c766/p")
set(re2_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(re2_INCLUDE_DIRS_RELWITHDEBINFO )
set(re2_RES_DIRS_RELWITHDEBINFO )
set(re2_DEFINITIONS_RELWITHDEBINFO )
set(re2_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(re2_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(re2_OBJECTS_RELWITHDEBINFO )
set(re2_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(re2_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(re2_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(re2_LIB_DIRS_RELWITHDEBINFO "${re2_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(re2_BIN_DIRS_RELWITHDEBINFO )
set(re2_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(re2_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(re2_LIBS_RELWITHDEBINFO re2)
set(re2_SYSTEM_LIBS_RELWITHDEBINFO m pthread)
set(re2_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(re2_FRAMEWORKS_RELWITHDEBINFO )
set(re2_BUILD_DIRS_RELWITHDEBINFO )
set(re2_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(re2_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${re2_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${re2_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(re2_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${re2_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${re2_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${re2_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(re2_COMPONENTS_RELWITHDEBINFO )