########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

list(APPEND spdlog_COMPONENT_NAMES spdlog::spdlog)
list(REMOVE_DUPLICATES spdlog_COMPONENT_NAMES)
if(DEFINED spdlog_FIND_DEPENDENCY_NAMES)
  list(APPEND spdlog_FIND_DEPENDENCY_NAMES fmt)
  list(REMOVE_DUPLICATES spdlog_FIND_DEPENDENCY_NAMES)
else()
  set(spdlog_FIND_DEPENDENCY_NAMES fmt)
endif()
set(fmt_FIND_MODE "NO_MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(spdlog_PACKAGE_FOLDER_RELWITHDEBINFO "/n/home09/tkrishnan/.conan2/p/b/spdlo834c9c5d7273c/p")
set(spdlog_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(spdlog_INCLUDE_DIRS_RELWITHDEBINFO "${spdlog_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(spdlog_RES_DIRS_RELWITHDEBINFO )
set(spdlog_DEFINITIONS_RELWITHDEBINFO "-DSPDLOG_FMT_EXTERNAL"
			"-DSPDLOG_COMPILED_LIB")
set(spdlog_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(spdlog_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(spdlog_OBJECTS_RELWITHDEBINFO )
set(spdlog_COMPILE_DEFINITIONS_RELWITHDEBINFO "SPDLOG_FMT_EXTERNAL"
			"SPDLOG_COMPILED_LIB")
set(spdlog_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(spdlog_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(spdlog_LIB_DIRS_RELWITHDEBINFO "${spdlog_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(spdlog_BIN_DIRS_RELWITHDEBINFO )
set(spdlog_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(spdlog_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(spdlog_LIBS_RELWITHDEBINFO spdlog)
set(spdlog_SYSTEM_LIBS_RELWITHDEBINFO pthread)
set(spdlog_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(spdlog_FRAMEWORKS_RELWITHDEBINFO )
set(spdlog_BUILD_DIRS_RELWITHDEBINFO )
set(spdlog_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(spdlog_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${spdlog_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${spdlog_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(spdlog_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${spdlog_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${spdlog_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${spdlog_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(spdlog_COMPONENTS_RELWITHDEBINFO spdlog::spdlog)
########### COMPONENT spdlog::spdlog VARIABLES ############################################

set(spdlog_spdlog_spdlog_INCLUDE_DIRS_RELWITHDEBINFO "${spdlog_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(spdlog_spdlog_spdlog_LIB_DIRS_RELWITHDEBINFO "${spdlog_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(spdlog_spdlog_spdlog_BIN_DIRS_RELWITHDEBINFO )
set(spdlog_spdlog_spdlog_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(spdlog_spdlog_spdlog_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(spdlog_spdlog_spdlog_RES_DIRS_RELWITHDEBINFO )
set(spdlog_spdlog_spdlog_DEFINITIONS_RELWITHDEBINFO "-DSPDLOG_FMT_EXTERNAL"
			"-DSPDLOG_COMPILED_LIB")
set(spdlog_spdlog_spdlog_OBJECTS_RELWITHDEBINFO )
set(spdlog_spdlog_spdlog_COMPILE_DEFINITIONS_RELWITHDEBINFO "SPDLOG_FMT_EXTERNAL"
			"SPDLOG_COMPILED_LIB")
set(spdlog_spdlog_spdlog_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(spdlog_spdlog_spdlog_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(spdlog_spdlog_spdlog_LIBS_RELWITHDEBINFO spdlog)
set(spdlog_spdlog_spdlog_SYSTEM_LIBS_RELWITHDEBINFO pthread)
set(spdlog_spdlog_spdlog_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(spdlog_spdlog_spdlog_FRAMEWORKS_RELWITHDEBINFO )
set(spdlog_spdlog_spdlog_DEPENDENCIES_RELWITHDEBINFO fmt::fmt)
set(spdlog_spdlog_spdlog_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(spdlog_spdlog_spdlog_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(spdlog_spdlog_spdlog_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(spdlog_spdlog_spdlog_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${spdlog_spdlog_spdlog_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${spdlog_spdlog_spdlog_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${spdlog_spdlog_spdlog_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(spdlog_spdlog_spdlog_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${spdlog_spdlog_spdlog_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${spdlog_spdlog_spdlog_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")