########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(yaml-cpp_COMPONENT_NAMES "")
if(DEFINED yaml-cpp_FIND_DEPENDENCY_NAMES)
  list(APPEND yaml-cpp_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES yaml-cpp_FIND_DEPENDENCY_NAMES)
else()
  set(yaml-cpp_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(yaml-cpp_PACKAGE_FOLDER_RELWITHDEBINFO "/n/home09/tkrishnan/.conan2/p/b/yaml-b19f5cb365505/p")
set(yaml-cpp_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(yaml-cpp_INCLUDE_DIRS_RELWITHDEBINFO "${yaml-cpp_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(yaml-cpp_RES_DIRS_RELWITHDEBINFO )
set(yaml-cpp_DEFINITIONS_RELWITHDEBINFO "-DYAML_CPP_STATIC_DEFINE")
set(yaml-cpp_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(yaml-cpp_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(yaml-cpp_OBJECTS_RELWITHDEBINFO )
set(yaml-cpp_COMPILE_DEFINITIONS_RELWITHDEBINFO "YAML_CPP_STATIC_DEFINE")
set(yaml-cpp_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(yaml-cpp_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(yaml-cpp_LIB_DIRS_RELWITHDEBINFO "${yaml-cpp_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(yaml-cpp_BIN_DIRS_RELWITHDEBINFO )
set(yaml-cpp_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(yaml-cpp_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(yaml-cpp_LIBS_RELWITHDEBINFO yaml-cpp)
set(yaml-cpp_SYSTEM_LIBS_RELWITHDEBINFO m)
set(yaml-cpp_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(yaml-cpp_FRAMEWORKS_RELWITHDEBINFO )
set(yaml-cpp_BUILD_DIRS_RELWITHDEBINFO )
set(yaml-cpp_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(yaml-cpp_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${yaml-cpp_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${yaml-cpp_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(yaml-cpp_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${yaml-cpp_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${yaml-cpp_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${yaml-cpp_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(yaml-cpp_COMPONENTS_RELWITHDEBINFO )