#!/usr/bin/env julia
#
# tambo_shower test suite — regression baseline snapshot.
#
# Computes the Tier 4b summary statistics for every config's current output
# and writes them to baselines/<config>.toml. Run this ONCE against a run
# you trust; afterwards 4_assert.jl's Tier 4b compares new runs against it.
#
#   julia make_baselines.jl
#
# TAMBO_TEST_OUTDIR must point at the trusted run's output.

using Pkg
Pkg.activate(joinpath(@__DIR__, "..", ".."))   # the TamboSim package env

using TOML
using JSON3

include("assertions.jl")

const CONFIG_DIR   = joinpath(@__DIR__, "configs")
const BASELINE_DIR = joinpath(@__DIR__, "baselines")

function main()
    outdir = get(ENV, "TAMBO_TEST_OUTDIR", "")
    isempty(outdir) && error("TAMBO_TEST_OUTDIR is not set.")
    mkpath(BASELINE_DIR)

    for cpath in sort(filter(f -> endswith(f, ".toml"),
                             readdir(CONFIG_DIR; join = true)))
        name      = TOML.parsefile(cpath)["name"]
        jobs_file = joinpath(outdir, name, "jobs.jsonl")
        if !isfile(jobs_file)
            @warn "No jobs.jsonl — skipping" name
            continue
        end

        shower_dirs = String[]
        for line in eachline(jobs_file)
            isempty(strip(line)) && continue
            rec = JSON3.read(line)
            rec.decay_id == 99 && continue          # skip determinism repeat
            push!(shower_dirs, String(rec.outdir))
        end
        if isempty(shower_dirs)
            @warn "No showers — skipping" name
            continue
        end

        stats = summary_stats(shower_dirs)
        out   = joinpath(BASELINE_DIR, "$name.toml")
        open(out, "w") do io
            println(io, "# Tier 4b regression baseline for $name.")
            println(io, "# Generated by make_baselines.jl from a trusted run.")
            TOML.print(io, stats)
        end
        @info "Wrote baseline" name out
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
