# Geometry constants
"""Height factor for triangular grid spacing (ratio of row height to column spacing)."""
const TRIANGULAR_GRID_HEIGHT_FACTOR = sqrt(3) / 2

"""Default detection module dimensions [length, width, height] in meters."""
const DEFAULT_MODULE_EXTENT_M = SVector{3}([1.875, 0.8, 0.03])

"""
    SquareDetectionModule

Represents a square-shaped detection module.

# Fields
- `pos::SVector{3, Float64}`: The center position of the module.
- `rot::Rotation`: The rotation of the module in space.
- `extent::SVector{3, Float64}`: The side lengths of the module (x, y, z).
- `idx::Int`: An index to identify the module.
"""
struct SquareDetectionModule
  pos::SVector{3, Float64}
  rot::Rotation
  extent::SVector{3, Float64}
  idx::Int
end

"""
    CircularDetectionModule

Represents a circular-shaped detection module.

# Fields
- `pos::SVector{3, Float64}`: The center position of the module.
- `rot::Rotation`: The rotation of the module in space.
- `extent::SVector{2, Float64}`: The radius and height of the module.
- `idx::Int`: An index to identify the module.
"""
struct CircularDetectionModule
  pos::SVector{3, Float64}
  rot::Rotation
  extent::SVector{2, Float64}
  idx::Int
end

DetectionModule = Union{SquareDetectionModule, CircularDetectionModule}

# TODO add option for bounding box
"""
    inside(pt::SVector{3}, m::SquareDetectionModule) -> Bool

Checks if a point is inside a `SquareDetectionModule`.

The check is performed by transforming the point into the module's local coordinate
system and then checking if it lies within the module's extents.

# Arguments
- `pt::SVector{3}`: The point to check.
- `m::SquareDetectionModule`: The detection module.

# Returns
- `true` if the point is inside the module, `false` otherwise.
"""
function inside(pt::SVector{3}, m::SquareDetectionModule)
  offset = m.rot * (m.pos - pt)
  return all(abs.(offset) .< m.extent / 2)
end

"""
    inside(pt::SVector{3}, m::SquareDetectionModule, rmax::Real) -> Bool

Checks if a point is inside a `SquareDetectionModule` with a preliminary distance check.

This function first performs a coarse check by ensuring the point is within a sphere of
radius `rmax` around the module's center. If that passes, it calls the more precise
`inside(pt, m)` method.

# Arguments
- `pt::SVector{3}`: The point to check.
- `m::SquareDetectionModule`: The detection module.
- `rmax::Real`: The maximum radius for the initial coarse check.

# Returns
- `true` if the point is inside the module, `false` otherwise.
"""
function inside(pt::SVector{3}, m::SquareDetectionModule, rmax::Real)
    if any(abs.(pt .- m.pos) .> rmax)
        return false
    end
    #@show "Phase 2"
    return inside(pt, m)
end

"""
    inside(x_pt, y_pt, z_pt, m::SquareDetectionModule, rmax::Real) -> Bool

Checks if a point, given by its coordinates, is inside a `SquareDetectionModule`.

This is a convenience method that constructs a point vector and calls the corresponding
`inside` function. It also includes the coarse `rmax` check.

# Arguments
- `x_pt`, `y_pt`, `z_pt`: The coordinates of the point to check.
- `m::SquareDetectionModule`: The detection module.
- `rmax::Real`: The maximum radius for the initial coarse check.

# Returns
- `true` if the point is inside the module, `false` otherwise.
"""
function inside(x_pt, y_pt, z_pt, m::SquareDetectionModule, rmax::Real)
    if any(abs.(x_pt .- m.pos[1]) .> rmax) || any(abs.(y_pt .- m.pos[2]) .> rmax) || any(abs.(z_pt .- m.pos[3]) .> rmax)
        return false
    end
    return inside(SVector{3}([x_pt,y_pt,z_pt]), m)
end

"""
    make_triangle_grid(x0::Real, x1::Real, y0::Real, y1::Real, ds::Real) -> Vector{SVector{3, Float64}}

Creates a triangular grid of points in the xy-plane.

The grid is generated by placing points in rows, with each even-indexed row
offset horizontally to create a triangular pattern.

# Arguments
- `x0`, `x1`: The start and end x-coordinates for the grid.
- `y0`, `y1`: The start and end y-coordinates for the grid.
- `ds::Real`: The spacing between points in the grid.

# Returns
- A vector of `SVector{3, Float64}` representing the grid points.
"""
function make_triangle_grid(x0::Real, x1::Real, y0::Real, y1::Real, ds::Real)
  dy = ds * TRIANGULAR_GRID_HEIGHT_FACTOR
  ys = y0:dy:y1
  dx = ds
  xs = x0:dx:x1
  gridpoints = SVector{3, Float64}[]
  for x in xs for (idx, y) in enumerate(ys)
    offset = ds / 2
    if idx %2==0
       offset = 0
    end
    v = SVector{3}(x+offset, y, 0)
    push!(gridpoints, v)
  end end
  return gridpoints
end

"""
    make_detector_array(
        array_length::Real,
        ds::Real,
        altmin::Real,
        altmax::Real,
        geo::Geometry,
        ext::SVector{3}
    ) -> Vector{SquareDetectionModule}

Creates an array of `SquareDetectionModule`s arranged in a triangular grid on a mountain plain.

This function first generates a triangular grid in a 2D plane, then rotates it to align
with the mountain plain defined in the `Geometry` object. Points outside the specified
altitude range are filtered out. Finally, `SquareDetectionModule`s are created at the
remaining grid points.

# Arguments
- `array_length::Real`: The length of the detector array.
- `ds::Real`: The spacing between modules in the grid.
- `altmin::Real`, `altmax::Real`: The minimum and maximum altitude for the modules.
- `geo::Geometry`: The `Geometry` object containing information about the site.
- `ext::SVector{3}`: The extent (dimensions) of each detection module.

# Returns
- A vector of `SquareDetectionModule` objects.
"""
function make_detector_array(
    array_length::Real,
    ds::Real,
    altmin::Real,
    altmax::Real,
    geo::Geometry,
    ext::SVector{3}
)

    # Make a triangular grid in xy-plane
    plane = geo.plane

    #leave this, something with rotation makes the lengths work out such that
    #the lengths along the x axis 
    xys = make_triangle_grid(-2units.km, 2units.km, -array_length/2, array_length/2, ds)

    # Rotate it to align with the mountain plain
    r = RotZ(geo.plane.n̂.ϕ) * RotY(geo.plane.n̂.θ)
    #RotY(-minesite_normal_vec.θ) * RotZ(-minesite_normal_vec.ϕ)
    xyzs = [r * xy for xy in xys]
    # Remove points that are too high in z
    zmin = altmin - geo.tambo_offset[3]
    zmax = altmax - geo.tambo_offset[3]
    xyzs = filter(xyz -> zmin < xyz[3] && xyz[3] < zmax, xyzs)
    # Make the module list
    modules = SquareDetectionModule[]
    rot = RotY(-geo.plane.n̂.θ) * RotZ(-geo.plane.n̂.ϕ) # This makes the
    #ext = SVector{3}([1.875, 0.8, 0.03]) * units.m
    for (idx, xyz) in enumerate(xyzs)
        push!(modules, SquareDetectionModule(xyz, rot, ext, idx))
    end
    return modules
end

"""
    make_detector_array(
        length::Real,
        ds::Real,
        altmin::Real,
        altmax::Real,
        geo::Geometry,
    ) -> Vector{SquareDetectionModule}

A convenience wrapper for `make_detector_array` with a default module extent.

This function calls the main `make_detector_array` function with a default extent
of `[1.875, 0.8, 0.03]` meters.

# Arguments
- `length::Real`: The length of the detector array.
- `ds::Real`: The spacing between modules.
- `altmin::Real`, `altmax::Real`: The minimum and maximum altitude.
- `geo::Geometry`: The site `Geometry` object.

# Returns
- A vector of `SquareDetectionModule` objects.
"""
function make_detector_array(
    length::Real,
    ds::Real,
    altmin::Real,
    altmax::Real,
    geo::Geometry,
)
    ext = DEFAULT_MODULE_EXTENT_M * units.m
    return make_detector_array(length, ds, altmin, altmax, geo, ext)
end
